package models.pojos;
// Generated Nov 18, 2010 1:21:37 AM by Hibernate Tools 3.2.1.GA



/**
 * DondathangId generated by hbm2java
 */
public class DondathangId  implements java.io.Serializable {


     private int idkhachHang;
     private int idgioHang;

    public DondathangId() {
    }

    public DondathangId(int idkhachHang, int idgioHang) {
       this.idkhachHang = idkhachHang;
       this.idgioHang = idgioHang;
    }
   
    public int getIdkhachHang() {
        return this.idkhachHang;
    }
    
    public void setIdkhachHang(int idkhachHang) {
        this.idkhachHang = idkhachHang;
    }
    public int getIdgioHang() {
        return this.idgioHang;
    }
    
    public void setIdgioHang(int idgioHang) {
        this.idgioHang = idgioHang;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DondathangId) ) return false;
		 DondathangId castOther = ( DondathangId ) other; 
         
		 return (this.getIdkhachHang()==castOther.getIdkhachHang())
 && (this.getIdgioHang()==castOther.getIdgioHang());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdkhachHang();
         result = 37 * result + this.getIdgioHang();
         return result;
   }   


}


