package models.pojos;
// Generated Nov 18, 2010 1:20:56 PM by Hibernate Tools 3.2.1.GA



/**
 * GiohangSanpham generated by hbm2java
 */
public class GiohangSanpham  implements java.io.Serializable {


     
     private int idgioHang;
     private int idsanPham;

     private double donGia;
     private int soLuong;
     private double thanhTien;

    public GiohangSanpham() {
    }

    public GiohangSanpham( int giohang, int sanpham, double donGia, int soLuong, double thanhTien) {
       
       this.idgioHang = giohang;
       this.idsanPham = sanpham;
       this.donGia = donGia;
       this.soLuong = soLuong;
       this.thanhTien = thanhTien;
    }
    public int getIdgioHang() {
        return this.idgioHang;
    }

    public void setIdgioHang(int idgioHang) {
        this.idgioHang = idgioHang;
    }
    public int getIdsanPham() {
        return this.idsanPham;
    }

    public void setIdsanPham(int idsanPham) {
        this.idsanPham = idsanPham;
    }
   
    
    public int getGiohang() {
        return this.idgioHang;
    }
    
    public void setGiohang(int giohang) {
        this.idgioHang = giohang;
    }
    public int getSanpham() {
        return this.idsanPham;
    }
    
    public void setSanpham(int sanpham) {
        this.idsanPham = sanpham;
    }
    public double getDonGia() {
        return this.donGia;
    }
    
    public void setDonGia(double donGia) {
        this.donGia = donGia;
    }
    public int getSoLuong() {
        return this.soLuong;
    }
    
    public void setSoLuong(int soLuong) {
        this.soLuong = soLuong;
    }
    public double getThanhTien() {
        return this.thanhTien;
    }
    
    public void setThanhTien(double thanhTien) {
        this.thanhTien = thanhTien;
    }




}


