package models.pojos;
// Generated Nov 18, 2010 1:21:37 AM by Hibernate Tools 3.2.1.GA



/**
 * GiohangSanpham generated by hbm2java
 */
public class GiohangSanpham  implements java.io.Serializable {


     private GiohangSanphamId id;
     private Giohang giohang;
     private Sanpham sanpham;
     private double donGia;
     private int soLuong;
     private double thanhTien;

    public GiohangSanpham() {
    }

    public GiohangSanpham(GiohangSanphamId id, Giohang giohang, Sanpham sanpham, double donGia, int soLuong, double thanhTien) {
       this.id = id;
       this.giohang = giohang;
       this.sanpham = sanpham;
       this.donGia = donGia;
       this.soLuong = soLuong;
       this.thanhTien = thanhTien;
    }
   
    public GiohangSanphamId getId() {
        return this.id;
    }
    
    public void setId(GiohangSanphamId id) {
        this.id = id;
    }
    public Giohang getGiohang() {
        return this.giohang;
    }
    
    public void setGiohang(Giohang giohang) {
        this.giohang = giohang;
    }
    public Sanpham getSanpham() {
        return this.sanpham;
    }
    
    public void setSanpham(Sanpham sanpham) {
        this.sanpham = sanpham;
    }
    public double getDonGia() {
        return this.donGia;
    }
    
    public void setDonGia(double donGia) {
        this.donGia = donGia;
    }
    public int getSoLuong() {
        return this.soLuong;
    }
    
    public void setSoLuong(int soLuong) {
        this.soLuong = soLuong;
    }
    public double getThanhTien() {
        return this.thanhTien;
    }
    
    public void setThanhTien(double thanhTien) {
        this.thanhTien = thanhTien;
    }




}


