package models.pojos;
// Generated Nov 18, 2010 1:21:37 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Giohang generated by hbm2java
 */
public class Giohang  implements java.io.Serializable {


     private Integer id;
     private Set dondathangs = new HashSet(0);
     private Set giohangSanphams = new HashSet(0);

    public Giohang() {
    }

    public Giohang(Set dondathangs, Set giohangSanphams) {
       this.dondathangs = dondathangs;
       this.giohangSanphams = giohangSanphams;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Set getDondathangs() {
        return this.dondathangs;
    }
    
    public void setDondathangs(Set dondathangs) {
        this.dondathangs = dondathangs;
    }
    public Set getGiohangSanphams() {
        return this.giohangSanphams;
    }
    
    public void setGiohangSanphams(Set giohangSanphams) {
        this.giohangSanphams = giohangSanphams;
    }




}


