package models.pojos;
// Generated Nov 18, 2010 1:20:56 PM by Hibernate Tools 3.2.1.GA



/**
 * Dondathang generated by hbm2java
 */
public class Dondathang  implements java.io.Serializable {


     
     private int idkhachHang;
     private int idgioHang;

     private double tongTien;
     private int trangThai;

    public Dondathang() {
    }

    public Dondathang( int giohang, int khachhang, double tongTien, int trangThai) {
       
       this.idgioHang = giohang;
       this.idkhachHang = khachhang;
       this.tongTien = tongTien;
       this.trangThai = trangThai;
    }
    public int getIdkhachHang() {
        return this.idkhachHang;
    }

    public void setIdkhachHang(int idkhachHang) {
        this.idkhachHang = idkhachHang;
    }
    public int getIdgioHang() {
        return this.idgioHang;
    }

    public void setIdgioHang(int idgioHang) {
        this.idgioHang = idgioHang;
    }
   
    
    public int getGiohang() {
        return this.idgioHang;
    }
    
    public void setGiohang(int giohang) {
        this.idgioHang = giohang;
    }
    public int getKhachhang() {
        return this.idkhachHang;
    }
    
    public void setKhachhang(int khachhang) {
        this.idkhachHang = khachhang;
    }
    public double getTongTien() {
        return this.tongTien;
    }
    
    public void setTongTien(double tongTien) {
        this.tongTien = tongTien;
    }
    public int getTrangThai() {
        return this.trangThai;
    }
    
    public void setTrangThai(int trangThai) {
        this.trangThai = trangThai;
    }




}


