package models.pojos;
// Generated Nov 18, 2010 1:20:56 PM by Hibernate Tools 3.2.1.GA



/**
 * Giohang generated by hbm2java
 */
public class Giohang  implements java.io.Serializable {


     private int id;
     
     

    public Giohang() {
    }

    public Giohang(int id) {
       this.id = id;
       
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
}




