package models.pojos;
// Generated Nov 18, 2010 1:21:37 AM by Hibernate Tools 3.2.1.GA



/**
 * GiohangSanphamId generated by hbm2java
 */
public class GiohangSanphamId  implements java.io.Serializable {


     private int idgioHang;
     private int idsanPham;

    public GiohangSanphamId() {
    }

    public GiohangSanphamId(int idgioHang, int idsanPham) {
       this.idgioHang = idgioHang;
       this.idsanPham = idsanPham;
    }
   
    public int getIdgioHang() {
        return this.idgioHang;
    }
    
    public void setIdgioHang(int idgioHang) {
        this.idgioHang = idgioHang;
    }
    public int getIdsanPham() {
        return this.idsanPham;
    }
    
    public void setIdsanPham(int idsanPham) {
        this.idsanPham = idsanPham;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GiohangSanphamId) ) return false;
		 GiohangSanphamId castOther = ( GiohangSanphamId ) other; 
         
		 return (this.getIdgioHang()==castOther.getIdgioHang())
 && (this.getIdsanPham()==castOther.getIdsanPham());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdgioHang();
         result = 37 * result + this.getIdsanPham();
         return result;
   }   


}


