package models.pojos;
// Generated Nov 18, 2010 1:20:56 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Hang generated by hbm2java
 */
public class Hang  implements java.io.Serializable {


     private Integer id;
     private String ten;
     private Set sanphams = new HashSet(0);

    public Hang() {
    }

	
    public Hang(String ten) {
        this.ten = ten;
    }
    public Hang(String ten, Set sanphams) {
       this.ten = ten;
       this.sanphams = sanphams;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public Set getSanphams() {
        return this.sanphams;
    }
    
    public void setSanphams(Set sanphams) {
        this.sanphams = sanphams;
    }




}


