package models.pojos;
// Generated Nov 18, 2010 1:20:56 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Khachhang generated by hbm2java
 */
public class Khachhang  implements java.io.Serializable {


     
     private String ten;
     private String diaChi;
     private String email;
     private String username;
     private Integer loainguoidung;
     private String password;

    public Khachhang() {
    }

	
    public Khachhang(String ten, String email) {
        this.ten = ten;
        this.email = email;
    }
    public Khachhang(String username,String password,String ten, String diaChi, String email, Integer loainguoidung) {
        
       this.ten = ten;
       this.diaChi = diaChi;
       this.email = email;
       this.username = username;
       this.loainguoidung = loainguoidung;
       this.password = password;
    }
   
    
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    
    /**
     * @return the username
     */
    public String getUsername() {
        return username;
    }

    /**
     * @param username the username to set
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * @return the loainguoidung
     */
    public int getLoainguoidung() {
        return loainguoidung;
    }

    /**
     * @return the password
     */
    public String getPassword() {
        return password;
    }

    /**
     * @param loainguoidung the loainguoidung to set
     */
    public void setLoainguoidung(Integer loainguoidung) {
        this.loainguoidung = loainguoidung;
    }

    /**
     * @param password the password to set
     */
    public void setPassword(String password) {
        this.password = password;
    }




}


