package models.pojos;
// Generated Nov 18, 2010 1:21:37 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Loainguoidung generated by hbm2java
 */
public class Loainguoidung  implements java.io.Serializable {


     private Integer id;
     private String ten;
     private Set users = new HashSet(0);

    public Loainguoidung() {
    }

	
    public Loainguoidung(String ten) {
        this.ten = ten;
    }
    public Loainguoidung(String ten, Set users) {
       this.ten = ten;
       this.users = users;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


