package models.pojos;
// Generated Nov 18, 2010 1:21:37 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String username;
     private Loainguoidung loainguoidung;
     private String password;
     private Set khachhangs = new HashSet(0);

    public User() {
    }

	
    public User(String username, Loainguoidung loainguoidung, String password) {
        this.username = username;
        this.loainguoidung = loainguoidung;
        this.password = password;
    }
    public User(String username, Loainguoidung loainguoidung, String password, Set khachhangs) {
       this.username = username;
       this.loainguoidung = loainguoidung;
       this.password = password;
       this.khachhangs = khachhangs;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public Loainguoidung getLoainguoidung() {
        return this.loainguoidung;
    }
    
    public void setLoainguoidung(Loainguoidung loainguoidung) {
        this.loainguoidung = loainguoidung;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getKhachhangs() {
        return this.khachhangs;
    }
    
    public void setKhachhangs(Set khachhangs) {
        this.khachhangs = khachhangs;
    }




}


